### PR TITLE
Portworx volume encrypt

### PR DESCRIPTION
**Pull request by NathanielRose**
Encrypt volumes for portworx.
Required additional set up steps detailed in README.md

### CODE REVIEW

**Comment by andrebriggs** [comment]
@NathanielRose I assume we verify encryption using the `kubectl exec $PX_POD -n kube-system -- /opt/pwx/bin/pxctl volume list` command you reference? Do the existing tests work with this?

**Comment by andrebriggs** [comment]
@NathanielRose is this related to https://github.com/microsoft/bedrock/issues/529 ?

**Review by andrebriggs — CHANGES_REQUESTED** [review]
Waiting for response to previous comments

**Comment by NathanielRose** [comment]
Yes we verify volume encryption with that command. 

Yes Here are the logs from `internal.sh`
```
nmrose@DESKTOP-NU43M7R:/mnt/c/Users/naros/Desktop/Microsoft/fy20/stateful/portworx/final/fabrikate-kafka-sample/portworx-manual$ kubectl exec $PX_POD -n kube-system -- /opt/pwx/bin/pxctl volume list
ID                      NAME                                            SIZE    HA      SHARED  ENCRYPTED       IO_PRIORITY     STATUS                          SNAP-ENABLED
722076474827819484      pvc-7a16e412-beea-11e9-932e-661e100badb9        2 GiB   3       no      yes             LOW             up - attached on 10.10.1.35     no
584189335564075361      pvc-7a17611a-beea-11e9-932e-661e100badb9        2 GiB   3       no      yes             LOW             up - attached on 10.10.1.4      no
912121283719282787      pvc-7a192b66-beea-11e9-932e-661e100badb9        2 GiB   3       no      yes             LOW             up - attached on 10.10.1.66     no
3883428304792215        pvc-a3930d1c-beee-11e9-932e-661e100badb9        20 GiB  3       no      yes             LOW             up - attached on 10.10.1.4      no
633927160748792651      pvc-a3935824-beee-11e9-932e-661e100badb9        20 GiB  3       no      yes             LOW             up - attached on 10.10.1.35     no
57016135568605396       pvc-a3937166-beee-11e9-932e-661e100badb9        20 GiB  3       no      yes             LOW             up - attached on 10.10.1.66     no
nmrose@DESKTOP-NU43M7R:/mnt/c/Users/naros/Desktop/Microsoft/fy20/stateful/portworx/final/fabrikate-kafka-sample/portworx-manual$ cd ..
nmrose@DESKTOP-NU43M7R:/mnt/c/Users/naros/Desktop/Microsoft/fy20/stateful/portworx/final/fabrikate-kafka-sample$ cd test/
nmrose@DESKTOP-NU43M7R:/mnt/c/Users/naros/Desktop/Microsoft/fy20/stateful/portworx/final/fabrikate-kafka-sample/test$ ./internaltest.sh 
secret/mirror-maker-cluster-ca-cert created
kafkatopic.kafka.strimzi.io/test created
kafkatopic.kafka.strimzi.io/test-one-rep created
kafkatopic.kafka.strimzi.io/test-replication created
kafkauser.kafka.strimzi.io/test-user created
statefulset.apps/kafkaclient created
01145eea-dc35-43fc-af69-c761ac429bf8
\033[1;33mTest Topic: topic-01145eea-dc35-43fc-af69-c761ac429bf8\033[0m
OpenJDK 64-Bit Server VM warning: If the number of processors is expected to increase from one, then you should configure the number of parallel GC threads appropriately using -XX:ParallelGCThreads=N
Created topic topic-01145eea-dc35-43fc-af69-c761ac429bf8.
Creating Input Message file.
413de4ee-b783-48a8-82ff-1168761fde5d
db76d7b0-3b84-4d2a-8e30-dacbde3c4b77
0dac087f-ea9b-4e5b-bf57-6307b85561d1
308b9d5a-02fc-4598-ad8c-c2877d3213da
919b33bf-8219-4eaa-82cf-4993a7df306a
2acb1e74-91e2-4f3e-801b-18a58cacabf0
4031b748-1f4b-4593-8b15-c29e7937bbc5
8f1ef3b1-8ce6-49ee-9542-4abfba83dd09
dd58e8ea-7690-493c-ac71-5f03251179cd
b3ff10f0-5017-4c66-b190-8bc4ef1c6ce3
>>>>>>>>>>>listing topics
OpenJDK 64-Bit Server VM warning: If the number of processors is expected to increase from one, then you should configure the number of parallel GC threads appropriately using -XX:ParallelGCThreads=N
__consumer_offsets
_schemas
connect-cluster-configs
connect-cluster-offsets
connect-cluster-status
test
test-one-rep
test-replication
topic-01145eea-dc35-43fc-af69-c761ac429bf8
topic-3e57cf33-6d77-42d6-9f10-adbabf264b35
topic-c8084d47-9d1e-4fea-8305-85fcc599ae62
topic-fd5c8ef9-c733-418b-a818-78876bbea890
./internaltest.sh: line 56: 26004 Terminated              kubectl exec -n kafka -i kafkaclient-0 -- bin/kafka-console-consumer.sh --bootstrap-server kcluster-kafka-bootstrap:9092 --topic $TESTING_TOPIC --from-beginning > $MESSAGE_OUTPUT_FILE
kafkatopic.kafka.strimzi.io "test" deleted
kafkatopic.kafka.strimzi.io "test-one-rep" deleted
kafkatopic.kafka.strimzi.io "test-replication" deleted
kafkauser.kafka.strimzi.io "test-user" deleted
statefulset.apps "kafkaclient" deleted
secret "mirror-maker-cluster-ca-cert" deleted
deleting test topic
kubectl exec -n kafka -ti kcluster-kafka-0 --container kafka -- bin/kafka-topics.sh --zookeeper localhost:2181 --delete --topic topic-01145eea-dc35-43fc-af69-c761ac429bf8
OpenJDK 64-Bit Server VM warning: If the number of processors is expected to increase from one, then you should configure the number of parallel GC threads appropriately using -XX:ParallelGCThreads=N
Topic topic-01145eea-dc35-43fc-af69-c761ac429bf8 is marked for deletion.
Note: This will have no impact if delete.topic.enable is not set to true.
listing topics after deletion
OpenJDK 64-Bit Server VM warning: If the number of processors is expected to increase from one, then you should configure the number of parallel GC threads appropriately using -XX:ParallelGCThreads=N
__consumer_offsets
_schemas
connect-cluster-configs
connect-cluster-offsets
connect-cluster-status
topic-3e57cf33-6d77-42d6-9f10-adbabf264b35
topic-c8084d47-9d1e-4fea-8305-85fcc599ae62
topic-fd5c8ef9-c733-418b-a818-78876bbea890
\033[0;32mTest Passed!!! - All input messages are in the output!\033[0m
```

**Comment by NathanielRose** [comment]
Still working through the latest `./external.sh` with @mtarng.
Having wsl/sh/bash issues with kafkacat and config files.

**Comment by andrebriggs** [comment]
> Still working through the latest `./external.sh` with @mtarng.
> Having wsl/sh/bash issues with kafkacat and config files.

@NathanielRose so we should wait until that part is done?

**Comment by NathanielRose** [comment]
`./extrenal.sh` is Passing as well @andrebriggs . Here is the output. This is ready for merge
```
ID                      NAME                                            SIZE    HA      SHARED  ENCRYPTED       IO_PRIORITY     STATUS                          SNAP-ENABLED
331879809837870162      pvc-26e102ce-c033-11e9-ace8-2652ce4d20a8        20 GiB  3       no      yes             LOW             up - attached on 10.240.0.4     no
996709944607020295      pvc-26e1372d-c033-11e9-ace8-2652ce4d20a8        20 GiB  3       no      yes             LOW             up - attached on 10.240.0.6     no
386916664599178688      pvc-26e6d5a9-c033-11e9-ace8-2652ce4d20a8        20 GiB  3       no      yes             LOW             up - attached on 10.240.0.5     no
607242511495737217      pvc-39e52eaa-c030-11e9-ace8-2652ce4d20a8        2 GiB   3       no      yes             LOW             up - attached on 10.240.0.4     no
889973468853929846      pvc-39e561ce-c030-11e9-ace8-2652ce4d20a8        2 GiB   3       no      yes             LOW             up - attached on 10.240.0.6     no
907268111283017399      pvc-39e5ca8d-c030-11e9-ace8-2652ce4d20a8        2 GiB   3       no      yes             LOW             up - attached on 10.240.0.5     no
nmrose@DESKTOP-NU43M7R:/mnt/c/Users/naros/Desktop/Microsoft/fy20/stateful/portworx/final/fabrikate-kafka-sample/test$ ./externaltest.sh 
13.72.225.52
9094
\033[1;33mKafka External Address: 13.72.225.52:9094\033[0m
f968bc94-51ff-443d-b378-ee7440a293ce
\033[1;33mTest Topic: topic-f968bc94-51ff-443d-b378-ee7440a293ce\033[0m
kafkatopic.kafka.strimzi.io/topic-f968bc94-51ff-443d-b378-ee7440a293ce created
kafkatopic.kafka.strimzi.io/topic-f968bc94-51ff-443d-b378-ee7440a293ce configured
\033[1;33mConfiguring Kafkacat without SSL\033[0m
Creating Input Message file.
f7bba815-dc39-459e-bb55-9520b5833977
32fa467a-af44-4d02-952f-c454a8d5130f
6ab5ed03-2b5b-47f9-8a8a-338d1d0f3444
62174062-ba0e-472a-9425-5f5d195889e0
7fe7c563-d85a-413f-b06d-210f997f315a
900bfcbd-ec93-4096-a064-91b49fd0112c
f1466d50-aca3-4bff-ad0b-6325f1f0306c
36f6ec30-b140-433c-8aa8-fafa3dedf7fe
77b43e5f-cd4b-4909-8c58-823aeb0cd700
f63ac401-6477-40f7-a82b-1828b0f913cc
% Reading configuration from file temp/topic-f968bc94-51ff-443d-b378-ee7440a293ce/kafkacat.config
% Reading configuration from file temp/topic-f968bc94-51ff-443d-b378-ee7440a293ce/kafkacat.config
% Reached end of topic topic-f968bc94-51ff-443d-b378-ee7440a293ce [1] at offset 4
% Reached end of topic topic-f968bc94-51ff-443d-b378-ee7440a293ce [2] at offset 4
% Reached end of topic topic-f968bc94-51ff-443d-b378-ee7440a293ce [0] at offset 2
kafkatopic.kafka.strimzi.io "topic-f968bc94-51ff-443d-b378-ee7440a293ce" deleted
\033[0;32mTest Passed!!! - All input messages are in the output!\033[0m
```

**Comment by andrebriggs** [comment]
@NathanielRose  Just to be clear if one follows the instructions [here](https://github.com/sayar/fabrikate-kafka-sample/blob/4f1408eeddb668a2e784c3ae3f958da373a5d4bc/portworx-manual/README.md#setting-up-portworx-manually) from your PR, then goes and deploys the rest of the Kafka sample components via Fabrikate it will all work together?

Also I updated the task list [here](https://github.com/microsoft/bedrock/issues/529). Is this accurate?

**Comment by NathanielRose** [comment]
@andrebriggs that's correct. Those instructions will work with the latest master branch, tests and Kafka manifests. Rg 'nr-bare0test0rg' and cluster 'nr-px-final-test' is the resource I used to get the logs mentioned in the previous comment.

Correct, 1 of the security tasks from issue #529 has been completed. (volume encryption)

**Review by andrebriggs — DISMISSED** [review]

**Comment by andrebriggs** [comment]
@NathanielRose Looks like we are missing a link [here](https://github.com/sayar/fabrikate-kafka-sample/blob/4f1408eeddb668a2e784c3ae3f958da373a5d4bc/portworx-manual/README.md#backing-up-and-restoring-a-kafka-node-through-snapshots)
> For more details on how to snapshot volumes using stork check out here.

Let's fix and merge

Also what is the status on the [snapshot tests](https://github.com/microsoft/bedrock/issues/511#issuecomment-521405227)?

**Review by andrebriggs — APPROVED** [review]

**Comment by NathanielRose** [comment]
@andrebriggs Broken link has been fixed.
I'll push another PR for the finalized Failover Tests. I'll provide instructions for Snapshots with 3dsnaps. Snapshot testing would be better with a multicluster scenario.

**Review by andrebriggs — APPROVED** [review]

**Pull request merged**
