### PR TITLE
performance test updates

### PR DESCRIPTION
**Pull request by cnadolny**
done:
- added zookeeper sidecar to be able to connect to Strimzi Kafka Zookeeper service internally
- removed unused perf tests
- added sleep in between each test to prevent timeouts from trying to run sequential tests too quickly

### CODE REVIEW

**Comment by andrebriggs** [comment]
@cnadolny just for my understanding what is this test targeting exactly? Why couldn't we go through Kafka to exercise a performance test?

**Comment by cnadolny** [comment]
> 
> 
> @cnadolny just for my understanding what is this test targeting exactly? Why couldn't we go through Kafka to exercise a performance test?

It's the same perf tests that we've been using before. It was a feature within the Strimzi operator to not expose access to Zookeeper via the Kubernetes service, so this change adds a workaround to that so that it is accessible via a sidecar and all tests are able to be run. Also added some cleanup to the tests like adding a sleep in between each and formatting.

**Comment by NathanielRose** [comment]
@cnadolny Are the correct ports being targeted for ZK since we are using TLS? 9094 vs 9092

**Comment by cnadolny** [comment]
> 
> 
> @cnadolny Are the correct ports being targeted for ZK since we are using TLS? 9094 vs 9092

Zookeeper is no longer being targeted - I changed the consumer perf tests to target the Kafka broker (secured with TLS) on port 9093, same as the producer perf tests!

**Review by mtarng — APPROVED** [review]

**Pull request merged**
